# -*- coding: utf-8 -*-
#
# S1Tiling documentation build configuration file, created by
# sphinx-quickstart on Mon Sep 14 12:38:14 2020.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys
import subprocess

from s1tiling.libs.otbtools import otb_version

# import sphinx_rtd_theme
sys.path.insert(0, os.path.abspath('..'))

BASEDIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.realpath(__file__))))
metadata = {}
with open(os.path.join(BASEDIR, "s1tiling", "__meta__.py"), "r") as f:
    exec(f.read(), metadata)

def setup(app):
    # app.add_stylesheet("css/otb_theme.css")
    # Customize read the docs theme a bit with a custom css
    # and a custom version selection widget
    # taken from https://stackoverflow.com/a/43186995/5815110
    app.add_js_file("js/versions.js")
    app.add_config_value('ultimate_replacements', {}, True)
    app.connect('source-read', ultimateReplace)

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_carousel.carousel',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    "sphinx.ext.autosectionlabel",
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.inheritance_diagram',
    "sphinx_rtd_theme",
    'm2r2',
    'sphinx.ext.mathjax',
    'sphinx_click',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = metadata['__title__']
copyright = metadata['__copyright__']
author = metadata['__author__']

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = metadata['__version__']
git_version = os.environ.get('CI_COMMIT_REF_NAME') or subprocess.check_output('git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD', shell=True).strip().decode('ascii')
# The full version, including alpha/beta/rc tags.
tag_re = re.compile(r'^\d+\.\d+.*')
match = tag_re.match(git_version)
if match:
    # Releasing a tag
    print(f'This is a tag: {git_version}')
    release = git_version
    version_type = 'tags'
else:
    # Releasing a branch
    print(f'This is a branch: {git_version}')
    release = version+'-'+git_version
    version_type = 'heads'

docker_version = f"{version}-ubuntu-otb{otb_version()}"  # Before overriding version!!
lmod_version   = f"{version}-otb{otb_version()}"  # Before overriding version!!
version        = git_version
release_badge  = release.replace('-', '--')

print(f'Using {git_version=}')
print(f"{docker_version=}")

rst_prolog = """
.. |Badge doc| image:: https://img.shields.io/badge/docs-{release_badge}-brightgreen?logo=readthedocs
   :alt: Documentation
   :target: https://s1-tiling.pages.orfeo-toolbox.org/s1tiling/{release}/

.. |Badge CI| image:: https://img.shields.io/gitlab/pipeline-status/s1-tiling%2Fs1tiling?gitlab_url=https%3A%2F%2Fgitlab.orfeo-toolbox.org&branch={git_version}&label=CI%20{git_version}&logo=gitlab
   :alt: {git_version} pipeline Status
   :target: https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling/-/pipelines?page=1&scope=branches&ref={git_version}

.. |Badge coverage| image:: https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling/badges/{git_version}/coverage.svg
   :alt: {git_version} branch coverage
   :target: https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling/-/pipelines?page=1&scope=branches&ref={git_version}

.. |Badge docker| image:: https://img.shields.io/docker/v/cnes/s1tiling/{docker_version}?logo=docker
   :alt: Dockerhub
   :target: https://hub.docker.com/r/cnes/s1tiling
""".format(release=release, release_badge=release_badge, git_version=git_version, docker_version=docker_version)


## Enable replacements in code-block and other places
# https://github.com/sphinx-doc/sphinx/issues/4054
def ultimateReplace(app, docname, source):
    result = source[0]
    for key in app.config.ultimate_replacements:
        result = result.replace(key, app.config.ultimate_replacements[key])
    source[0] = result

reference_otb_version = '9.1.1'

print(f'Reference OTB Version: {reference_otb_version} -- used in documentation')

## And the replacements to use with {KEY} instead of |KEY|
RE_BRACKETS = re.compile(r'{.*?}|\(.*?\)')
def as_sample_mustache(fmt: str) -> str:
    fmt = re.sub(RE_BRACKETS, r'{\g<0>}', fmt)
    fmt = f":samp:`{fmt}`"
    return fmt

from s1tiling.libs.configuration    import DEFAULT_FNAME_FMTS as fname_fmt
from s1tiling.libs.utils.formatters import ResilientFormatter

example_keys = {
    'flying_unit_code' : 's1(a|b|c)',
    'tile_name'        : '{tilename}',
    'polarisation'     : '{polarity}',
    'orbit_direction'  : '(ASC|DES)'
}

ultimate_replacements = {
    "{REF_OTB_VERSION}"                : reference_otb_version,
    "{VERSION}"                        : version,
    "{VERSION_TYPE}"                   : version_type,
    "{DOCKER_VERSION}"                 : docker_version,
    "{LMOD_VERSION}"                   : lmod_version,
    "{fname_fmt_concatenation}"        : as_sample_mustache(fname_fmt['concatenation']),

    "{fname_fmt_filtered}"             : as_sample_mustache(fname_fmt['filtered']),
    "{fname_fmt_filtered_calib}"       : as_sample_mustache(fname_fmt['filtered_calib']),
    "{fname_fmt_filtered_lia}"         : as_sample_mustache(ResilientFormatter().format(fname_fmt['filtered_calib'], calibration_type='NormLim')),
    "{fname_fmt_filtered_rtc}"         : as_sample_mustache(ResilientFormatter().format(fname_fmt['filtered_calib'], calibration_type='GammaNaughtRTC')),

    "{fname_fmt_ia_product}"           : as_sample_mustache(fname_fmt['ia_product']),

    "{fname_fmt_lia_product}"          : as_sample_mustache(fname_fmt['lia_product']),
    "{fname_fmt_lia_corrected}"        : as_sample_mustache(fname_fmt['lia_corrected']),

    "{fname_fmt_gamma_area}"           : as_sample_mustache(fname_fmt['gamma_area']),
    "{fname_fmt_gamma_area_corrected}" : as_sample_mustache(fname_fmt['gamma_area_corrected']),

    "{fname_ex_concatenation_day}"     : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['concatenation'], **example_keys, acquisition_stamp='{YYYYMMDD}txxxxxx')),
    "{fname_ex_concatenation_time}"    : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['concatenation'], **example_keys, acquisition_stamp='{YYYYMMDD}t{hhmmss}')),

    "{fname_ex_deg_ia}"                : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['ia_product'], **example_keys, IA_kind='IA')),
    "{fname_ex_cos_ia}"                : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['ia_product'], **example_keys, IA_kind='cos_IA')),
    "{fname_ex_sin_ia}"                : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['ia_product'], **example_keys, IA_kind='sin_IA')),
    "{fname_ex_tan_ia}"                : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['ia_product'], **example_keys, IA_kind='tan_IA')),

    "{fname_ex_deg_lia}"               : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['lia_product'], **example_keys, LIA_kind='LIA')),
    "{fname_ex_sin_lia}"               : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['lia_product'], **example_keys, LIA_kind='sin_LIA')),

    "{fname_ex_gamma_area}"            : as_sample_mustache(
        ResilientFormatter().format(fname_fmt['gamma_area'], **example_keys)),
}

# ######################################################################
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Authorize duplicated label automatically generated from section titles
# https://stackoverflow.com/a/77577337/15934
suppress_warnings = ['autosectionlabel.*']


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'default'
# html_theme = 'nature'
# html_theme = 'bizstyle'
html_theme = 'sphinx_rtd_theme'
# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()+"/sphinx_rtd_theme/static/"]
# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # "show_prev_next": False,
    # 'stickysidebar': True,
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Override tables width from RTD theme, and other options
html_css_files = [
    'theme_overrides.css'
]

#
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'S1Tilingdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'S1Tiling.tex', u'S1Tiling Documentation',
     u'Tierry Koleck, Luc Hermitte', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 's1tiling', u'S1Tiling Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'S1Tiling', u'S1Tiling Documentation',
     author, 'S1Tiling', 'On demand Ortho-rectification of Sentinel-1 data on Sentinel-2 grid.',
     'Miscellaneous'),
]


# Configuration for intersphinx
intersphinx_mapping = {
    "Python": ("https://docs.python.org/3/", None),
    "Distributed": ("https://distributed.dask.org/en/latest/", None),
    "Dask": ("https://docs.dask.org/en/latest/", None),
    "Gdal": ("https://gdal.org/en/stable/", None),
    # "numpy": ("http://docs.scipy.org/doc/numpy", None),
    "eodag": ("https://eodag.readthedocs.io/en/stable/", None),


    # 'https://www.orfeo-toolbox.org/CookBook/': None,
    # Using CookBook from OTB 7.4 as it still distributes DiapOTB.
    "OTB": ('https://www.orfeo-toolbox.org/CookBook/', None),
    "OTB7": ('https://www.orfeo-toolbox.org/CookBook-7.4/', None),
}

# Search w/
# $> python -msphinx.ext.intersphinx https://gdal.org/objects.inv
# $> python -msphinx.ext.intersphinx https://www.orfeo-toolbox.org/CookBook/objects.inv
# $> python -msphinx.ext.intersphinx https://github.com/OSGeo/gdal-docs/blob/master/objects.inv | less


def autodoc_process_docstring(app, what, name, obj, options, lines):
    """
    Used to fix docstrings on-the-fly when generatiing pages with sphinx
    See https://github.com/sphinx-doc/sphinx/issues/10151
    """
    for i in range(len(lines)):
        # Auto convert np.whatever into numpy.whatever in docstrings for sphinx
        lines[i] = lines[i].replace("np.",        "numpy.")
        lines[i] = lines[i].replace("Callable[",  "~typing.Callable[")
        lines[i] = lines[i].replace("Generator[", "~typing.Generator[")
        lines[i] = lines[i].replace("Generic[",   "~typing.Generic[")
        lines[i] = lines[i].replace("Any",        "~typing.Any")
        lines[i] = lines[i].replace("Dict[",      "~typing.Dict[")
        lines[i] = lines[i].replace("Iterator[",  "~typing.Iterator[")
        lines[i] = lines[i].replace("List[",      "~typing.List[")
        lines[i] = lines[i].replace("Literal[",   "~typing.Literal[")
        lines[i] = lines[i].replace("KeysView[",  "~typing.KeysView[")
        lines[i] = lines[i].replace("Optional[",  "~typing.Optional[")
        lines[i] = lines[i].replace("Set[",       "~typing.Set[")
        lines[i] = lines[i].replace("Tuple[",     "~typing.Tuple[")
        lines[i] = lines[i].replace("Type[",      "~typing.Type[")
        lines[i] = lines[i].replace("TypeVar[",   "~typing.TypeVar[")
        lines[i] = lines[i].replace("Union[",     "~typing.Union[")


# Configuration for inheritance_diagram
inheritance_graph_attrs = dict(rankdir="TB")

graphviz_output_format = 'svg'
